### ISSUE TITLE
JavaScript integration

### ISSUE THREAD

**Issue by mudrd8mz** [IITBombayWeb/moodle-quizaccess_activateattempt#3]
It is discouraged to inject javascript into Moodle like this. Please follow the documentation https://docs.moodle.org/dev/Javascript_Modules on how to do it correctly.

**Comment by AmrataRamchandani** [comment]
New version of the plugin is uploaded with the required amd changes done on it.Please review it and let us know.Please review the code from the branch v1.0.3
